// Teste da API REST de Clínicas
@baseURL = http://localhost:4000/api/clinicas

// GET - Lista todos as clínicas
GET {{baseURL}}/?limit=10&skip=0
Content-Type: application/json

###
// GET - Lista a clinica pelo ID
GET {{baseURL}}/id/6655f46f67c5f2d1607cda19
Content-Type: application/json

###
// GET - Lista a clinica pelo nome
GET {{baseURL}}/nome/123
Content-Type: application/json

###
GET http://localhost:4000/api/clinicas/especialidades/1/uf/SP
Content-Type: application/json

###
// DELETE - Remove a clinica pelo id
DELETE {{baseURL}}/6655f46f67c5f2d1607cda19
Content-Type: application/json

###
// POST - Insere uma nova clínica
POST {{baseURL}}
Content-Type: application/json

{
  "nome": "Clinica dos Psicoterapeutas",
  "email": "contato@clinicadeteste1234.com",
  "data_cadastro": "01/01/1999",
  "telefone": "(15) 91111-1111",
  "classificacao": "8.7",
  "especialidades": [
    "1"
  ],
  "endereco": {
    "logradouro": "Rua C, 789",
    "numero": "789",
    "complemento": "nenhum",
    "bairro": "Centro",
    "cidade": "Cidade C",
    "estado": "Estado C",
    "uf": "SP",
    "cep": "34567-000",
    "localizacao": {
      "type": "Point",
      "coordinates": [
        -12.3456,
        -12.3456
      ]
    }
  }
}

###
// PUT - Altera uma clínica já existente

PUT {{baseURL}}/6666499b7c2ac099c0022d2a
Content-Type: application/json

{
  "_id": "6666499b7c2ac099c0022d2a",
  "nome": "Clinica de Terapia Integrada",
  "email": "contato@clinicadeteste1234.com",
  "data_cadastro": "01/01/1999",
  "telefone": "(15) 91111-1111",
  "classificacao": "8.7",
  "especialidades": [
    "1"
  ],
  "endereco": {
    "logradouro": "Rua C, 789",
    "numero": "789",
    "complemento": "nenhum",
    "bairro": "Centro",
    "cidade": "Cidade C",
    "estado": "Estado C",
    "uf": "SP",
    "cep": "34567-000",
    "localizacao": {
      "type": "Point",
      "coordinates": [
        -12.3456,
        -12.3456
      ]
    }
  }
}
