// Teste do endpoint dos usuários
@baseURL = http://localhost:4000/api/usuarios
//@baseURL = https://backend-rest-mongodb.vercel.app/api/usuarios

###
# @prompt senha
// POST - Cria um novo usuário
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Andre da Silva",
    "email": "andre_silva@gmail.com.br",
    "senha": "{{senha}}"
}

###
// GET - Lista todos os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY2NzUwNTBlM2M1NzE4MWYyYWZlMjk4In0sImlhdCI6MTcxODA1NDYwNywiZXhwIjoxNzE4OTE4NjA3fQ.yOsiM2qTtezlu-ZQH30FuLluEgd4RVDJTxYjSuR5m88

###
# @prompt senha
// POST - Efetua o login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "andre_silva@gmail.com.br",
    "senha": "{{senha}}"
}

###
// DELETE - Deleta um usuário pelo ID
DELETE {{baseURL}}/:id
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjY2NzUwNTBlM2M1NzE4MWYyYWZlMjk4In0sImlhdCI6MTcxODA1NDYwNywiZXhwIjoxNzE4OTE4NjA3fQ.yOsiM2qTtezlu-ZQH30FuLluEgd4RVDJTxYjSuR5m88
